name: GitHub Metrics

on:
  workflow_dispatch:  # Allows manual run
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
